# Generated by Django 6.0.2 on 2026-02-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        # User fields were moved into the `users` app initial migration.
        # This migration is kept as a no-op to preserve historical ordering.
    ]
