# Generated by Django 6.0.2 on 2026-02-19 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_user_is_agree_conditions_user_middle_name_user_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_agree_conditions',
        ),
    ]
