# Generated by Django 6.0.2 on 2026-02-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_is_agree_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agreed_privacy_policy',
            field=models.BooleanField(default=False),
        ),
    ]
