# Generated by Django 6.0.2 on 2026-02-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_user_is_agreed_privacy_policy'),
    ]

    operations = [
        # No-op: password reset fields were included in `users` initial migration.
    ]
