# Generated by Django 6.0.2 on 2026-02-20 03:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_user_password_reset_expires_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Type of Service',
                'verbose_name_plural': 'Types of Service',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='action_taken',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='client',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_purchased',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='department_organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='description_of_problem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='designation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='device_equipment',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ticket',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='ticket',
            name='job_status',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('pending', 'Pending'), ('under_warranty', 'Under Warranty'), ('chargeable', 'Chargeable'), ('for_quotation', 'For Quotation'), ('under_contract', 'Under Contract')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='landline',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='ticket',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='ticket',
            name='preferred_support_type',
            field=models.CharField(blank=True, choices=[('remote_online', 'Remote/Online'), ('onsite', 'Onsite'), ('chat', 'Chat'), ('call', 'Call')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='serial_no',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='stf_no',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='time_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type_of_service_others',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='version_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_attachments/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='type_of_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.typeofservice'),
        ),
    ]
