# Generated by Django 6.0.2 on 2026-02-20 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_user_password_reset_expires_and_more'),
    ]

    operations = [
        # No-op: password reset fields are managed in the `users` app migrations.
    ]
