# Generated by Django 6.0.2 on 2026-02-23 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_assignmentsession_ticket_current_session_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='title',
        ),
    ]
