# Generated by Django 6.0.2 on 2026-02-23 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_remove_ticket_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='description',
        ),
    ]
