# Generated by Django 6.0.2 on 2026-02-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_remove_ticket_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='brand',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ticket',
            name='has_warranty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='model_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ticket',
            name='product',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
