# Generated by Django 6.0.2 on 2026-02-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_merge_0006_0008'),
        ('tickets', '0009_remove_ticket_description'),
    ]

    operations = [
    ]
