# Generated by Django 6.0.2 on 2026-02-25 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_ticket_confirmed_by_admin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
    ]
