# Generated by Django 6.0.2 on 2026-03-02 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_alter_ticket_status_delete_csatsurvey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('entity', models.CharField(choices=[('User', 'User'), ('Ticket', 'Ticket'), ('TypeOfService', 'Type of Service'), ('EscalationLog', 'Escalation Log'), ('Attachment', 'Attachment'), ('Session', 'Session')], db_index=True, max_length=30)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ASSIGN', 'Assign'), ('ESCALATE', 'Escalate'), ('CLOSE', 'Close'), ('STATUS_CHANGE', 'Status Change'), ('PASSWORD_RESET', 'Password Reset')], db_index=True, max_length=20)),
                ('activity', models.TextField(help_text='Human-readable description of the action')),
                ('actor_email', models.EmailField(blank=True, default='', help_text='Snapshot of actor email at the time of the action', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, help_text='JSON diff of changed fields', null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'entity'], name='tickets_aud_timesta_ed0fb2_idx'), models.Index(fields=['actor', '-timestamp'], name='tickets_aud_actor_i_4cbd70_idx')],
            },
        ),
    ]
