# Generated by Django 6.0.2 on 2026-03-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ASSIGN', 'Assign'), ('ESCALATE', 'Escalate'), ('CLOSE', 'Close'), ('STATUS_CHANGE', 'Status Change'), ('PASSWORD_RESET', 'Password Reset'), ('PASS', 'Pass'), ('REVIEW', 'Review'), ('RESOLVE', 'Resolve'), ('UPLOAD', 'Upload'), ('CONFIRM', 'Confirm')], db_index=True, max_length=20),
        ),
    ]
