# Generated by Django 6.0.2 on 2026-03-03 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_add_audit_action_types'),
        ('tickets', '0017_knowledge_hub_publish_fields'),
    ]

    operations = [
    ]
