# Generated by Django 6.0.2 on 2026-03-04 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_merge_20260303_0812'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('landline', models.CharField(blank=True, max_length=30)),
                ('mobile_no', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('department_organization', models.CharField(blank=True, max_length=200)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['client_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_equipment', models.CharField(blank=True, max_length=300)),
                ('version_no', models.CharField(blank=True, max_length=100)),
                ('date_purchased', models.DateField(blank=True, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=200)),
                ('has_warranty', models.BooleanField(default=False)),
                ('product_name', models.CharField(blank=True, help_text='Product name (optional)', max_length=300)),
                ('brand', models.CharField(blank=True, help_text='Brand (optional)', max_length=300)),
                ('model_name', models.CharField(blank=True, help_text='Model (optional)', max_length=300)),
                ('sales_no', models.CharField(blank=True, help_text='Sales/invoice number', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='cascade_type',
            field=models.CharField(blank=True, choices=[('internal', 'Internal'), ('external', 'External')], default='', help_text='Cascading type selected by employee when resolving', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='estimated_resolution_days_override',
            field=models.PositiveIntegerField(blank=True, help_text='Override estimated resolution days when type of service is Others', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='observation',
            field=models.TextField(blank=True, default='', help_text='Employee observation before closing the ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='signature',
            field=models.TextField(blank=True, default='', help_text='Base64 encoded signature image'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='signed_by_name',
            field=models.CharField(blank=True, default='', help_text='Name of person who signed', max_length=200),
        ),
        migrations.AddField(
            model_name='typeofservice',
            name='estimated_resolution_days',
            field=models.PositiveIntegerField(default=0, help_text='Estimated number of days to resolve tickets of this service type (SLA basis)'),
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('call_start', models.DateTimeField(help_text='When the call started')),
                ('call_end', models.DateTimeField(blank=True, help_text='When the call ended', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-call_start'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='client_record',
            field=models.ForeignKey(blank=True, help_text='Link to existing client record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.client'),
        ),
        migrations.CreateModel(
            name='CSATFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('comments', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csat_given', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csat_received', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='csat_feedback', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'CSAT Feedback',
                'verbose_name_plural': 'CSAT Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='product_record',
            field=models.ForeignKey(blank=True, help_text='Link to product from global catalog', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.product'),
        ),
    ]
