# Generated by Django 6.0.2 on 2026-03-04 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_client_product_ticket_cascade_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('assignment', 'Ticket Assignment'), ('escalation', 'Escalation'), ('status_change', 'Status Change'), ('new_ticket', 'New Ticket'), ('sla_warning', 'SLA Warning'), ('closure', 'Closure'), ('message', 'New Message'), ('general', 'General')], default='general', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField(blank=True, default='')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(help_text='The user who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, help_text='The related ticket (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='tickets_not_recipie_8be10e_idx'), models.Index(fields=['recipient', 'is_read', '-created_at'], name='tickets_not_recipie_eda5c0_idx')],
            },
        ),
    ]
