# Generated by Django 6.0.2 on 2026-03-05 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='assignment_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.assignmentsession'),
        ),
    ]
