# Generated by Django 6.0.2 on 2026-03-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
