# Generated by Django 6.0.2 on 2026-03-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_add_is_archived_to_ticketattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='published_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
