# Generated by Django 6.0.2 on 2026-03-05 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_message_assignment_session_nullable'),
        ('tickets', '0022_ticketattachment_published_tags'),
    ]

    operations = [
    ]
