# Generated by Django 6.0.2 on 2026-03-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_merge_20260305_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='linked_tickets',
            field=models.ManyToManyField(blank=True, help_text='Related tickets (same problem)', to='tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ASSIGN', 'Assign'), ('ESCALATE', 'Escalate'), ('CLOSE', 'Close'), ('STATUS_CHANGE', 'Status Change'), ('PASSWORD_RESET', 'Password Reset'), ('PASS', 'Pass'), ('REVIEW', 'Review'), ('RESOLVE', 'Resolve'), ('UPLOAD', 'Upload'), ('CONFIRM', 'Confirm'), ('OBSERVE', 'Submit for Observation'), ('UNRESOLVED', 'Mark Unresolved'), ('LINK', 'Link Tickets')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('escalated', 'Escalated (Internal)'), ('escalated_external', 'Escalated (External)'), ('pending_closure', 'Pending Closure'), ('for_observation', 'For Observation'), ('unresolved', 'Unresolved')], default='open', max_length=20),
        ),
    ]
