# Generated by Django 6.0.2 on 2026-03-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_ticket_linked_tickets_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sales_no',
            field=models.CharField(blank=True, default='', help_text='Sales / Invoice number associated with this ticket', max_length=200),
        ),
    ]
