# Generated by Django 6.0.2 on 2026-03-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0034_convert_client_sales_fields_to_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sales_representative',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
