# Generated by Django 6.0.2 on 2026-03-23 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_alter_client_sales_representative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='date_purchased',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='device_equipment',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='has_warranty',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='others',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sales_no',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='serial_no',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='version_no',
        ),
        migrations.AddField(
            model_name='product',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client that owns this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='tickets.client'),
        ),
        migrations.AddField(
            model_name='product',
            name='date_purchased',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='others',
            field=models.TextField(blank=True, default=''),
        ),
    ]
