# Generated by Django 6.0.2 on 2026-05-07 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0046_product_firmware_and_software_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(blank=True, null=True)),
                ('time_responded', models.TimeField(blank=True, null=True)),
                ('time_completed', models.TimeField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, default='', max_length=60)),
                ('type_of_service', models.CharField(blank=True, default='', max_length=200)),
                ('type_of_support', models.CharField(blank=True, default='', max_length=120)),
                ('description_of_trouble', models.TextField(blank=True, default='')),
                ('action_taken', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Under Warranty', 'Under Warranty'), ('Under Quotation', 'Under Quotation'), ('Chargeable', 'Chargeable'), ('Under Contract', 'Under Contract')], default='Pending', max_length=40)),
                ('product_name', models.CharField(blank=True, default='', max_length=300)),
                ('product_title', models.CharField(blank=True, default='', max_length=300)),
                ('device_equipment', models.CharField(blank=True, default='', max_length=200)),
                ('serial_no', models.CharField(blank=True, default='', max_length=200)),
                ('product_remarks', models.CharField(blank=True, default='', max_length=400)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='service_reports/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_reports', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_reports', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
