# Generated by Copilot on 2026-05-07

from django.db import migrations, models
from django.utils import timezone


def assign_service_report_numbers(apps, schema_editor):
    ServiceReport = apps.get_model('tickets', 'ServiceReport')
    sequence_by_prefix = {}

    reports = ServiceReport.objects.all().order_by('created_at', 'id')
    for report in reports:
        source_date = report.report_date
        if source_date is None:
            created_at = report.created_at
            if created_at is not None:
                source_date = created_at.date()
            else:
                source_date = timezone.localdate()

        prefix = f"SR-MT-{source_date.strftime('%Y%m%d')}"
        sequence_by_prefix[prefix] = sequence_by_prefix.get(prefix, 0) + 1
        report.sr_no = f"{prefix}{sequence_by_prefix[prefix]:04d}"
        report.save(update_fields=['sr_no'])


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0047_servicereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereport',
            name='sr_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.RunPython(assign_service_report_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='servicereport',
            name='sr_no',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
