from django.db import models
from django.conf import settings
from django.utils import timezone
from .ticket import Ticket


class CallLog(models.Model):
    """Records each call made by admin to a client during ticket creation."""
    ticket = models.ForeignKey(Ticket, null=True, blank=True, on_delete=models.SET_NULL, related_name='call_logs')
    admin = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='call_logs', on_delete=models.CASCADE)
    client_name = models.CharField(max_length=200, blank=True)
    phone_number = models.CharField(max_length=30, blank=True)
    call_start = models.DateTimeField(help_text='When the call started')
    call_end = models.DateTimeField(null=True, blank=True, help_text='When the call ended')
    notes = models.TextField(blank=True, default='')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-call_start']

    @property
    def duration_seconds(self):
        if self.call_start and self.call_end:
            return (self.call_end - self.call_start).total_seconds()
        return None

    def __str__(self):
        return f"Call #{self.id} by {self.admin.username} at {self.call_start}"


class FeedbackRating(models.Model):
    """Admin feedback on employee performance before closing a ticket."""
    RATING_CHOICES = [
        (1, 'Very Poor'),
        (2, 'Poor'),
        (3, 'Average'),
        (4, 'Good'),
        (5, 'Excellent'),
    ]

    ticket = models.OneToOneField(Ticket, on_delete=models.CASCADE, related_name='feedback_rating')
    employee = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='feedback_ratings_received', on_delete=models.CASCADE)
    admin = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='feedback_ratings_given', on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(choices=RATING_CHOICES)
    comments = models.TextField(blank=True, default='')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Feedback Rating'
        verbose_name_plural = 'Feedback Ratings'

    def __str__(self):
        return f"Feedback Rating for {self.ticket.stf_no}: {self.rating}/5 by {self.admin.username}"


class ServiceReport(models.Model):
    """Service report generated by admin/technical for a ticket."""
    SR_SEQUENCE_WIDTH = 4

    STATUS_PENDING = 'Pending'
    STATUS_DONE = 'Done'
    STATUS_UNDER_WARRANTY = 'Under Warranty'
    STATUS_UNDER_QUOTATION = 'Under Quotation'
    STATUS_CHARGEABLE = 'Chargeable'
    STATUS_UNDER_CONTRACT = 'Under Contract'
    STATUS_CHOICES = [
        (STATUS_PENDING, 'Pending'),
        (STATUS_DONE, 'Done'),
        (STATUS_UNDER_WARRANTY, 'Under Warranty'),
        (STATUS_UNDER_QUOTATION, 'Under Quotation'),
        (STATUS_CHARGEABLE, 'Chargeable'),
        (STATUS_UNDER_CONTRACT, 'Under Contract'),
    ]

    sr_no = models.CharField(max_length=30, unique=True, blank=True)
    ticket = models.ForeignKey('Ticket', null=True, blank=True, on_delete=models.SET_NULL, related_name='service_reports')
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL, related_name='service_reports')

    report_date = models.DateField(null=True, blank=True)
    time_responded = models.TimeField(null=True, blank=True)
    time_completed = models.TimeField(null=True, blank=True)

    contact_no = models.CharField(max_length=60, blank=True, default='')
    type_of_service = models.CharField(max_length=200, blank=True, default='')
    type_of_support = models.CharField(max_length=120, blank=True, default='')

    description_of_trouble = models.TextField(blank=True, default='')
    action_taken = models.TextField(blank=True, default='')
    remarks = models.TextField(blank=True, default='')
    status = models.CharField(max_length=40, choices=STATUS_CHOICES, blank=True, default=STATUS_PENDING)

    # Product snapshot fields (only chosen fields to show on report)
    product_name = models.CharField(max_length=300, blank=True, default='')
    product_title = models.CharField(max_length=300, blank=True, default='')
    device_equipment = models.CharField(max_length=200, blank=True, default='')
    serial_no = models.CharField(max_length=200, blank=True, default='')
    product_remarks = models.CharField(max_length=400, blank=True, default='')

    # Optional attachment (single file for simplicity)
    attachment = models.FileField(upload_to='service_reports/%Y/%m/%d/', null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    @classmethod
    def _get_sr_prefix(cls, for_date=None):
        if for_date is None:
            for_date = timezone.localdate()
        if hasattr(for_date, 'date'):
            for_date = for_date.date()
        return f"SR-MT-{for_date.strftime('%Y%m%d')}"

    @classmethod
    def get_next_sr_no(cls, for_date=None):
        prefix = cls._get_sr_prefix(for_date)
        seq = 1
        for sr_no in cls.objects.filter(sr_no__startswith=prefix).values_list('sr_no', flat=True):
            suffix = str(sr_no)[len(prefix):]
            if suffix.isdigit():
                seq = max(seq, int(suffix) + 1)
        return f'{prefix}{seq:0{cls.SR_SEQUENCE_WIDTH}d}'

    def save(self, *args, **kwargs):
        if not self.sr_no:
            self.sr_no = self.get_next_sr_no(self.report_date)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.sr_no or f'ServiceReport #{self.id}'} for {self.ticket.stf_no if self.ticket else 'N/A'}"


class ServiceReportAttachment(models.Model):
    """Additional files attached to a service report."""
    service_report = models.ForeignKey(ServiceReport, related_name='attachments', on_delete=models.CASCADE)
    file = models.FileField(upload_to='service_reports/%Y/%m/%d/')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_at', 'id']

    def __str__(self):
        return f"ServiceReportAttachment #{self.id} for {self.service_report.sr_no if self.service_report else 'N/A'}"
