# Generated by Django 6.0.2 on 2026-02-20 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_reset_expires',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_reset_token',
        ),
    ]
