# Generated by Django 6.0.2 on 2026-03-10 07:45

import uuid
from django.db import migrations, models


def populate_recovery_keys(apps, schema_editor):
    """Generate unique recovery keys for all existing users."""
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        raw = uuid.uuid4().hex + uuid.uuid4().hex
        user.recovery_key = '-'.join(raw[i:i+4] for i in range(0, 32, 4))
        user.save(update_fields=['recovery_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_profile_picture'),
    ]

    operations = [
        # Step 1: Add the field without unique constraint
        migrations.AddField(
            model_name='user',
            name='recovery_key',
            field=models.CharField(blank=True, default='', help_text='Unique recovery key for password reset', max_length=39),
        ),
        # Step 2: Populate existing users with unique keys
        migrations.RunPython(populate_recovery_keys, migrations.RunPython.noop),
        # Step 3: Now enforce uniqueness
        migrations.AlterField(
            model_name='user',
            name='recovery_key',
            field=models.CharField(blank=True, help_text='Unique recovery key for password reset (xxxx-xxxx-xxxx-xxxx-xxxx-xxxx-xxxx-xxxx)', max_length=39, unique=True),
        ),
    ]
