# Generated by Django 6.0.2 on 2026-04-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_hash_user_recovery_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Technical Staff'), ('sales', 'Sales'), ('admin', 'Supervisor'), ('superadmin', 'Superadmin')], default='employee', max_length=12),
        ),
    ]
